apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: registry-controller-{{ repl_suffix }}
spec:
  replicas: 1
  selector:
    name: registry
    suffix: {{ repl_suffix }}
  template:
    metadata:
      labels:
        name: registry
        suffix: {{ repl_suffix }}
    spec:
      containers:
        - name: registry
          image: registry:2
          volumeMounts:
            - name: registry
              mountPath: /registry
          livenessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 2
      volumes:
        - name: registry
          nfs:
            server: {{ master_ip }}
            path: /export/registry
            readOnly: false
