apiVersion: v1beta3
kind: Pod
metadata:
  name: registry
spec:
  containers:
    - name: registry
      image: registry:2
      volumeMounts:
        - name: registry
          mountPath: /registry
  volumes:
    - name: registry
      emptyDir: {}
