apiVersion: v1beta3
kind: Service
metadata:
  name: dockci-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  publicIPs: {{ external_ips | to_json }}
  selector:
    name: dockci
