- hosts: masters
  sudo: yes
  vars_files:
    - vars.yaml
  tasks:
    - include: 't_base.yaml'

    - lineinfile: dest=/etc/kubernetes/apiserver regexp='KUBE_API_ADDRESS *='
                  line='KUBE_API_ADDRESS="--address=0.0.0.0"'
      notify: restart kube-master services
    - lineinfile: dest=/etc/kubernetes/controller-manager regexp='KUBELET_ADDRESSES *='
                  line='KUBELET_ADDRESSES=""'
      notify: restart kube-master services
    - lineinfile: dest=/etc/etcd/etcd.conf regexp='ETCD_LISTEN_CLIENT_URLS *='
                  line='ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:4001"'
      notify: restart etcd service

    - service: name={{ item }} state=started enabled=yes
      with_items:
        - etcd
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
    - command: 'curl -s -L http://127.0.0.1:4001/v2/keys/coreos.com/network/config -XPUT -d value="{\"Network\": \"4.0.0.0/8\", \"SubnetLen\": 24, \"Backend\": {\"Type\": \"vxlan\"}}"'
    - service: name=flanneld state=started enabled=yes
      notify: restart flannel

  handlers:
    - name: restart kube-minion services
      debug: msg="Not on kube-minion"
    - name: restart kube-master services
      service: name={{ item }} state=restarted enabled=yes
      with_items:
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
    - name: restart etcd service
      service: name=etcd state=restarted enabled=yes

    - include: h_base.yaml
    - name: restart kube-minion services 2
      debug: msg="Not on kube-minion"
