- hosts: all
  sudo: yes
  gather_facts: no
  vars_files:
    - vars.yaml
  tasks:
    - selinux: state=disabled
      notify: restart node

  handlers:
    - name: restart node
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: true
      notify: wait for node
    - name: wait for node
      local_action: wait_for port=22
                             host="{{ inventory_hostname }}"
                             search_regex=OpenSSH
                             delay=5
